# Generated by Django 3.2 on 2023-02-02 19:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='В логине разрешены только буквы, цифры и символы  @.+-_', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
