# Generated by Django 3.2 on 2023-02-12 13:12

import django.core.validators
from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230207_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='В логине разрешены только буквы, цифры и символы  @.+-_', regex='^[\\w.@+-]+\\Z'), users.validators.validate_username_not_me], verbose_name='Логин'),
        ),
    ]
